language: node_js
dist: trusty
sudo: required
node_js:
  - "node"
virtualenv:
  system_site_packages: true
install:
 - git clone github.com/mozilla/web-ext/
 - cd web-ext
script:
 - mv ../get-nps ./
 - bash get-nps
