language: node_js
dist: trusty
sudo: required
node_js:
  - "node"
virtualenv:
  system_site_packages: true
install:
 - git clone https://github.com/xtoolkit/Micon/
 - cd Micon
script:
 - bash get-nps
