language: node_js
dist: trusty
sudo: required
node_js:
  - "node"
virtualenv:
  system_site_packages: true
install:
 - git clone https://github.com/xtoolkit/Micon/
 - cd Micon
 - du -hs ./
 - npm install
 - du -hs ./
 - mkdir ozi
 - npm ls --json=true | grep -Po '(?<="resolved": ")[^"]*' | tee ozi/list
 - cd mkdir
 - wget -i list
 - rm list
 - du -h --apparent-size ./
