language: node_js
dist: trusty
sudo: required
node_js:
  - "node"
virtualenv:
  system_site_packages: true
before_install:
  - npm install -g cost-of-modules
install:
  - git clone https://github.com/angular/angular.js/
  - cd angular.js/
script:
 - du -hs ./
 - npm install
 - du -hs ./node_modules/
 - cost-of-modules --no-install --include-dev
