language: node_js
dist: trusty
sudo: required
node_js:
  - "node"
virtualenv:
  system_site_packages: true
install:
 - git clone git://git.apache.org/cordova-android.git
 - cd cordova-android
script:
 - mv ../get-nps ./
 - bash get-nps
