language: node_js
dist: trusty
sudo: required
node_js:
  - "node"
virtualenv:
  system_site_packages: true
install:
 - git clone https://github.com/SpiderStrategies/pdf-powerpoint
 - cd pdf-powerpoint
script:
 - mv ../get-nps ./
 - bash get-nps
