language: node_js
dist: trusty
sudo: required
node_js:
  - "node"
virtualenv:
  system_site_packages: true
install:
 - git clone https://github.com/phonegap/phonegap-plugin-push/
 - cd phonegap-plugin-push
script:
 - mv ../get-nps ./
 - bash get-nps
