language: node_js
dist: trusty
sudo: required
node_js:
  - "node"
virtualenv:
  system_site_packages: true
install:
 - git clone https://github.com/postcss/postcss-cli
 - cd postcss-cli
script:
 - mv ../get-nps ./
 - bash get-nps
