#!/bin/bash

# git size in disk
echo "git size in disk:"
du -hs ./

# install npm package
echo "instaling npm packages"
npm install > /dev/null

# git size in disk after npm install
echo "git size in disk after npm install:"
du -hs ./

# download tgz and calc
mkdir ozi
npm ls --json=true | grep -Po '(?<="resolved": ")[^"]*' | tee ozi/list > /dev/null
cd ozi
wget -i list > /dev/null
rm list
echo "all tgz orginal size:"
du -h --apparent-size ./
